
# Work profile additions.
[kubernetes]
disabled = false

[[kubernetes.contexts]]
context_pattern = "arn:aws:eks:.*:cluster/(?P<var_cluster>.+)"
context_alias = "$var_cluster (eks)"

[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<var_cluster>[\\w-]+)"
context_alias = "$var_cluster (gke)"
