add_newline = false

# Disable cloud related noise.
[azure]
disabled = true
[aws]
disabled = true
[gcloud]
disabled = true

# Tune the prompt look and feel.
[character]
error_symbol = "[✖](bold red)"

[cmd_duration]
disabled = true

[directory]
truncate_to_repo = false

[line_break]
disabled = true

[username]
show_always = true

[kubernetes]
disabled = false
[kubernetes.context_aliases]
"arn:aws:eks:.*:cluster/(?P<var_cluster>.+)" = "$var_cluster (eks)"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "$var_cluster (gke)"

[package]
disabled = true
