add_newline = false

# Disable dloud related noise.
[azure]
disabled = true
[aws]
disabled = true
[gcloud]
disabled = true

# Tune the prompt look and feel.
[character]
error_symbol = "[✖](bold red)"

[cmd_duration]
disabled = true

[directory]
truncate_to_repo = false

[line_break]
disabled = true

[username]
show_always = true
