.DEFAULT_GOAL := install
.PHONY: build clean install uninstall

# TODO: Detect the terminal being used.
# TODO: add support for MacOS (probably iTerm2?).

# Targets
build:

clean:

install:
	gnome/theme-nord/src/nord.sh
	@echo "--> Don't forget to update the terminal current and default theme"

uninstall:
	@echo "--> 1. Set a new current and default theme"
	@echo "--> 2. Delete the nord theme from your terminal"
