.PHONY: install uninstall

# Top-level targets.
install:
	gnome/theme-nord/src/nord.sh
	@echo "--> Don't forget to update the terminal current and default theme"

uninstall:
	@echo "--> 1. Set a new current and default theme"
	@echo "--> 2. Delete the nord theme from your terminal"
	@read -p 'Done? '
